"""DPO (Direct Preference Optimization) — alignment without a reward model.

Terminology:
    Alignment: Making the model behave helpfully, harmlessly, and honestly.
        After instruction tuning (SFT), the model can follow instructions but may
        produce verbose, incorrect, or unhelpful code. Alignment fixes this.

    RLHF (Reinforcement Learning from Human Feedback): The old approach.
        Train a separate reward model, then use PPO to optimize against it.
        Complex, unstable, requires 3 models in memory simultaneously.

    DPO (Direct Preference Optimization): The modern replacement.
        Skips the reward model entirely. Instead, directly optimizes the policy
        using pairs of (chosen, rejected) responses.

    Paper: "Direct Preference Optimization: Your Language Model is Secretly a Reward Model"
           Rafailov et al. (2023). https://arxiv.org/abs/2305.18290

    How DPO works:
        1. Collect preference pairs: (prompt, chosen_response, rejected_response)
           "Chosen" = the better response. "Rejected" = the worse one.

        2. DPO loss pushes the model to:
           - Increase P(chosen) relative to the reference model
           - Decrease P(rejected) relative to the reference model

        3. The loss is:
           L = -log(σ(β * (log π(chosen)/π_ref(chosen) - log π(rejected)/π_ref(rejected))))

           Where π is the trained model, π_ref is the frozen reference (pre-DPO) model,
           and β controls how much the model can diverge from the reference.

    Reference model (π_ref): A frozen copy of the model BEFORE DPO training.
        Acts as an anchor — prevents the model from collapsing to degenerate behavior
        by penalizing large divergences from the starting point.

    β (beta): KL-divergence penalty strength. Higher β = model stays closer to reference.
        Typical: β = 0.1. Too low → model collapses. Too high → no learning.

Usage:
    This module provides the DPO loss and training loop.
    Preference data can be generated by having the SFT model produce multiple
    responses and selecting the best one (or using existing preference datasets).
"""

import torch
import torch.nn.functional as F
from torch.utils.data import Dataset


class PreferencePairDataset(Dataset):
    """Dataset of (prompt, chosen, rejected) triples for DPO.

    Args:
        examples: list of dicts with keys: prompt, chosen, rejected
        tokenizer: HuggingFace tokenizer
        max_length: maximum sequence length
    """

    def __init__(self, examples, tokenizer, max_length=512):
        self.examples = examples
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.examples)

    def __getitem__(self, idx):
        ex = self.examples[idx]

        chosen_text = ex["prompt"] + ex["chosen"]
        rejected_text = ex["prompt"] + ex["rejected"]

        chosen_enc = self.tokenizer(
            chosen_text, truncation=True, max_length=self.max_length,
            padding="max_length", return_tensors="pt",
        )
        rejected_enc = self.tokenizer(
            rejected_text, truncation=True, max_length=self.max_length,
            padding="max_length", return_tensors="pt",
        )

        return {
            "chosen_input_ids": chosen_enc["input_ids"].squeeze(0),
            "chosen_attention_mask": chosen_enc["attention_mask"].squeeze(0),
            "rejected_input_ids": rejected_enc["input_ids"].squeeze(0),
            "rejected_attention_mask": rejected_enc["attention_mask"].squeeze(0),
        }


def compute_log_probs(model, input_ids, attention_mask, labels):
    """Compute per-token log probabilities for a sequence.

    Args:
        model: language model
        input_ids: (batch, seq_len)
        attention_mask: (batch, seq_len)
        labels: (batch, seq_len) — same as input_ids shifted

    Returns:
        sum of log probs over non-padded tokens: (batch,)
    """
    outputs = model(input_ids=input_ids, attention_mask=attention_mask)
    logits = outputs.logits  # (batch, seq_len, vocab_size)

    # Shift: predict next token
    shift_logits = logits[:, :-1, :]
    shift_labels = labels[:, 1:]
    shift_mask = attention_mask[:, 1:]

    # Per-token log probs
    log_probs = F.log_softmax(shift_logits, dim=-1)
    token_log_probs = torch.gather(log_probs, 2, shift_labels.unsqueeze(2)).squeeze(2)

    # Mask out padding tokens and sum
    masked_log_probs = token_log_probs * shift_mask.float()
    return masked_log_probs.sum(dim=1)  # (batch,)


def dpo_loss(model, ref_model, batch, beta=0.1, device="cuda"):
    """Compute the DPO loss for a batch of preference pairs.

    Args:
        model: the model being trained (π)
        ref_model: frozen reference model (π_ref)
        batch: dict with chosen/rejected input_ids, attention_mask
        beta: KL penalty strength
        device: computation device

    Returns:
        loss: scalar DPO loss
        metrics: dict with chosen/rejected rewards for logging
    """
    chosen_ids = batch["chosen_input_ids"].to(device)
    chosen_mask = batch["chosen_attention_mask"].to(device)
    rejected_ids = batch["rejected_input_ids"].to(device)
    rejected_mask = batch["rejected_attention_mask"].to(device)

    # Compute log probs under current model
    pi_chosen = compute_log_probs(model, chosen_ids, chosen_mask, chosen_ids)
    pi_rejected = compute_log_probs(model, rejected_ids, rejected_mask, rejected_ids)

    # Compute log probs under reference model (no gradients)
    with torch.no_grad():
        ref_chosen = compute_log_probs(ref_model, chosen_ids, chosen_mask, chosen_ids)
        ref_rejected = compute_log_probs(ref_model, rejected_ids, rejected_mask, rejected_ids)

    # DPO loss: -log(σ(β * (log(π/π_ref)(chosen) - log(π/π_ref)(rejected))))
    chosen_reward = beta * (pi_chosen - ref_chosen)
    rejected_reward = beta * (pi_rejected - ref_rejected)

    loss = -F.logsigmoid(chosen_reward - rejected_reward).mean()

    metrics = {
        "chosen_reward": chosen_reward.mean().item(),
        "rejected_reward": rejected_reward.mean().item(),
        "reward_margin": (chosen_reward - rejected_reward).mean().item(),
    }

    return loss, metrics
